export enum Routes {
    BASE_API_ROUTE = '/api',
    INVOICES_ROUTE = '/invoices',
    AUTH_ROUTE = '/auth',
    AUTH_CALLBACK_ROUTE = '/callback',
    AUTH_GETUSER_ROUTE = '/user',
    AUTH_LOGOUT_ROUTE = '/logout',
    UPLOAD_ROUTE = '/upload',
    PRODUCTS_ROUTE = '/products',
    SALE_PRODUCTS_ROUTE = '/sale-products',
    CUSTOMERS_ROUTE = '/customers',
    CODE_TRANSLATIONS_ROUTE = '/code-translations',
    ORDERS_ROUTE = '/orders',
    ORDERS_ROUTE_REFRESH = '/refresh',
}
