export enum PermissionsEnum {
    READ_TEMPLATES = 'read:templates',
    CREATE_TEMPLATES = 'create:templates',
    UPDATES_TEMPLATES = 'updates:templates',
    DELETE_TEMPLATES = 'delete:templates',
    READ_CAMPAIGNS = 'read:campaigns',
    CREATE_CAMPAIGNS = 'create:campaigns',
    UPDATE_CAMPAIGNS = 'update:campaigns',
    DELETE_CAMPAIGNS = 'delete:campaigns',
    READ_EMAIL_PROVIDERS = 'read:eMailProviders',
    CREATE_EMAIL_PROVIDERS = 'create:eMailProviders',
    UPDATE_EMAIL_PROVIDERS = 'update:eMailProviders',
    DELETE_EMAIL_PROVIDERS = 'delete:eMailProviders',
    CREATE_USERS = 'create:users',
    READ_USERS = 'read:users',
    UPDATE_USERS = 'update:users',
    DELETE_USERS = 'delete:users',
    UPDATE_MANAGER_ROLE = 'update:manager-role',
    UPDATE_OWNER_ROLE = 'update:owner-role',
    EXECUTE_CAMPAIGNS = 'execute:campaigns',
    APPROVE_TEMPLATES = 'approve:templates',
    SCHEDULE_CAMPAIGN = 'schedule:campaign',
}
